# shellcheck disable=SC1000-SC9999

name: Test Self-hosted Runner

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  setup-runner:
    name: Test-Setup Self Hosted Runner
    runs-on: ubuntu-latest
    outputs:
      instance_id: ${{ steps.create-runner.outputs.instance_id }}
      runner_name: ${{ steps.create-runner.outputs.runner_name }}

    steps:
      - name: Create Runner
        uses: sustainable-computing-io/aws_ec2_self_hosted_runner@main
        id: create-runner
        env:
          ACTION: "create"
          AWS_REGION: ${{ secrets.AWS_REGION }}
          GITHUB_TOKEN: ${{ secrets.GH_SELF_HOSTED_RUNNER_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SECURITY_GROUP_ID: ${{ secrets.AWS_SECURITY_GROUP_ID }}
          GITHUB_REPO: ${{ github.repository }}
          AMI_ID: "ami-0e4d0bb9670ea8db0"
          INSTANCE_TYPE: "t2.micro"
          CREATE_S3_BUCKET: "false"
          SPOT_INSTANCE_ONLY: "true"

      - name: Print Output
        id: output
        run: |
          echo "instance_id ${{ steps.create-runner.outputs.instance_id }}"
          echo "instance_ip ${{ steps.create-runner.outputs.instance_ip }}"
          echo "runner_name ${{ steps.create-runner.outputs.runner_name }}"
    
  test-runner:
    needs: setup-runner
    name: GitHub Self Hosted Runner Tests
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          export INSTANCE_ID="${{ needs.setup-runner.outputs.instance_id }}"
          echo "Running tests on self-hosted runner with instance ${INSTANCE_ID}"
          uname -a # 
          cat /etc/os-release 
          cat /proc/cpuinfo 
  
  destroy-runner:
    if: always()
    needs: [setup-runner, test-runner]
    name: Destroy Self Hosted Runner
    steps:
      - name: unregister runner
        id: unregister
        uses: sustainable-computing-io/aws_ec2_self_hosted_runner@main
        env:
          ACTION: "unregister"
          RUNNER_NAME: ${{ needs.setup-runner.outputs.runner_name }}
          GITHUB_TOKEN: ${{ secrets.GH_SELF_HOSTED_RUNNER_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}

      - name: terminate instance
        id: terminate
        env:
          ACTION: "terminate"
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          INSTANCE_ID: ${{ needs.setup-runner.outputs.instance_id }}
